[package]
org = "ayash"
name = "blockingqueue"
version = "0.1.0"
authors = ["ayash"]
export = ["blockingqueue"]
keywords = ["blockingqueue", "concurrency","thread-safe"]
repository = "https://github.com/chathushkaayash/ballerina-blocking-queue"
license = ["Apache-2.0"]
distribution = "2201.10.2"

[build-options]
observabilityIncluded = true


[[platform.java17.dependency]]
groupId = "io.ayash"
artifactId = "blockingqueue-native"
version = "0.1.0"
path = "../native/build/libs/blockingqueue-native-0.1.0-SNAPSHOT.jar"

