name: Pull request build

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Install Ballerina
      - name: Install Ballerina
        uses: ballerina-platform/setup-ballerina@v1
        with:
          version: 2201.10.2

      # Build the Gradle project
      - name: Set Gradlew Permissions
        run: chmod +x ./gradlew
      - name: Build with Gradle
        env:
          packageUser: ${{ secrets.packageUser }}
          packagePAT: ${{ secrets.packagePAT }}
        run: ./gradlew clean build
