name: Pull request build

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      # Install Ballerina
      - name: Set up Ballerina
        uses: ballerina-platform/github-action@v1
        with:
          ballerina-version: "2201.10.2"

      # Build the Gradle project
      - name: Build with Gradle
        run: ./gradlew build
